# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kitty < Formula
  desc ""
  homepage ""
  version "0.6.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ImSingee/kitty/releases/download/v0.6.3/kitty-0.6.3-darwin.amd64.tar.gz"
      sha256 "4c408045b7507f0b5a518b7d98ad4508034d74d0449ab8c4601fc44c7c3618e8"

      define_method(:install) do
        bin.install "kitty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ImSingee/kitty/releases/download/v0.6.3/kitty-0.6.3-darwin.arm64.tar.gz"
      sha256 "9adfdda79b8341123bcd69a016f6fef2126a3ef4f2bf383ce60aa2de2eb8eacd"

      define_method(:install) do
        bin.install "kitty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ImSingee/kitty/releases/download/v0.6.3/kitty-0.6.3-linux.amd64.tar.gz"
      sha256 "9d6daef32b43c85377c7d02eae51e25dee488126f79e5c7e8048251106cde6b9"
      define_method(:install) do
        bin.install "kitty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ImSingee/kitty/releases/download/v0.6.3/kitty-0.6.3-linux.arm64.tar.gz"
      sha256 "8d80ed1ee32fb39465e575c9671812649ea75219e5b04846fa83049153da9e72"
      define_method(:install) do
        bin.install "kitty"
      end
    end
  end

  test do
    system "#{bin}/foo --version"
  end
end
