# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kitty < Formula
  desc ""
  homepage ""
  version "0.1.0-alpha.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ImSingee/kitty/releases/download/v0.1.0-alpha.3/kitty-0.1.0-alpha.3-darwin.arm64.tar.gz"
      sha256 "4512c1da5de36f50e8d667289e220323d5a29cbcb7830516f7104991d2a43510"

      def install
        bin.install "kitty"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ImSingee/kitty/releases/download/v0.1.0-alpha.3/kitty-0.1.0-alpha.3-darwin.amd64.tar.gz"
      sha256 "c556626392dcc3d9628fc0c9ee780cd7ec6a8f5b93b1e236b9e05effc8f61456"

      def install
        bin.install "kitty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ImSingee/kitty/releases/download/v0.1.0-alpha.3/kitty-0.1.0-alpha.3-linux.arm64.tar.gz"
      sha256 "1cde34c19441fc10fb7f82dd721c51de86be795ecd2c10a96ac8e0220e14a389"

      def install
        bin.install "kitty"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ImSingee/kitty/releases/download/v0.1.0-alpha.3/kitty-0.1.0-alpha.3-linux.amd64.tar.gz"
      sha256 "123ee00a93477cd8e5b6d8f4ad98cc6e4dafb5c650a8c4bbceafd9c6b15ae196"

      def install
        bin.install "kitty"
      end
    end
  end

  test do
    system "#{bin}/foo --version"
  end
end
